### ISSUE TITLE
Why not using Autolykos 2 instead of KawPow

### ISSUE THREAD

**Issue by frandmnc** [NeoxaChain/Neoxa#10]
Autolykos is a very GPU-oriented power efficient algorithm, why going with KawPow?

**Comment by hbroer** [comment]
Because this is just a Ravencoin clone, which was a Bitcoin clone, and it is only made for pump and dump. It will be abandoned like Ravencoin. 99% sure of that.

**Comment by hbroer** [comment]
Oh I wasn't correct. They got the code without referencing from
https://github.com/HiveProject2021/Hivecoin

That project (which also looks dead) cloned the Ravencoin code and that's again a Bitcoin clone. Yay thats like having siblings as parents. :-D
