### ISSUE TITLE
Neoxa on macbook

### ISSUE THREAD

**Issue by DarioSavic** [NeoxaChain/Neoxa#11]
Neoxa wallet on mac m1 doesn't show some text on a page. You can see in the pictures the missing send button and other functionality.

<img width="1071" alt="Screenshot at Sep 12 00-00-25" src="https://user-images.githubusercontent.com/42929531/189550646-308abf64-b6e5-46f5-a204-07411cdaf680.png">

<img width="1068" alt="Screenshot at Sep 12 00-03-36" src="https://user-images.githubusercontent.com/42929531/189550719-4f5263e2-523f-40fb-a2b8-e1faae5da466.png">

**Comment by shinary2** [comment]
Just change to Dark mode in settings and screen.

**Comment by DarioSavic** [comment]
Thanks @shinary2 , it helped ;)

**Comment by NikheelR97** [comment]
Would it not be better to allow the application to pull the OS system mode and auto apply it?
