### ISSUE TITLE
recovery help

### ISSUE THREAD

**Issue by Deadjester70** [NeoxaChain/Neoxa#12]
I have my seed phrase but cannont for the life of me remember my passphrase, how do i recover it?

**Comment by shinary2** [comment]
close wallet, backup your wallet.dat in %appdata%\neoxa, restart wallet and enter your 12 words (and recoverypassphrase if set one) in new window choose new passphrase for unlocking wallet. 
after sync go to tools>repair wallet> rebuild index and your funds should be available.

**Comment by UncipheredLLC** [comment]
Hi @Deadjester70 

If you're still having problems and @shinary2's advice didn't get your wallet open, we're happy to review. Check out https://www.unciphered.com and we're happy to check for free after you fill out our intake form.
