### ISSUE TITLE
Error on install.sh

### ISSUE THREAD

**Issue by bpatelTWO** [NeoxaChain/Neoxa#17]
Followed the steps 100% on both a clean install of 20.04 and 18.04 and when got to install.sh got a permission denied.

and help would be appreciated

**Comment by dogemackenzie** [comment]
are you logged in as the "pool" user when trying to run it? I didnt have any issues with this part, my issues came after this

**Comment by bpatelTWO** [comment]
Yes I think, unless doing it wrong. 

su - pool
Password:
pool@neoxa:~$ sudo apt install git -y
[sudo] password for pool:
Reading package lists... Done
Building dependency tree
Reading state information... Done
git is already the newest version (1:2.17.1-1ubuntu0.12).
0 upgraded, 0 newly installed, 0 to remove and 28 not upgraded.
pool@neoxa:~$ cd ~
pool@neoxa:~$ git config --global http.https://gopkg.in.followRedirects true
pool@neoxa:~$ git clone https://github.com/NeoxaChain/kawpow-pool
fatal: destination path 'kawpow-pool' already exists and is not an empty directory.
pool@neoxa:~$ cd kawpow-pool/
pool@neoxa:~/kawpow-pool$ ./install.sh
-su: ./install.sh: Permission denied

**Comment by automed-os** [comment]
I had to do this to make it work
$ chmod 755 ./install.sh
$ ./install.sh

**Comment by bpatelTWO** [comment]
Thanks, its installing

**Comment by dogemackenzie** [comment]
Yeah, exactly chmod the file. They beat me to the punch
