### ISSUE TITLE
Running it in headless linux machine

### ISSUE THREAD

**Issue by guorenxi** [NeoxaChain/Neoxa#2]
Hi,

Need to obtain an wallet address, not founding any guides on running the nexoa-cli in a headless linux (debian) machine. Please provide instructions.

Thanks.

**Comment by matischroder** [comment]
I did it. 
Follow this steps:
1. Download the qt zip [neoxa-qt-linux64.zip](https://github.com/NeoxaChain/Neoxa/releases/tag/v1.0.3) from the current repo

**Comment by jak83A** [comment]
i get a crash on Ubuntu 20.04 

./neoxa-qt

"Floating point exception (core dumped)"
