### ISSUE TITLE
Neoxa balance showing in Watch only mode.

### ISSUE THREAD

**Issue by Sibghatshaikhh** [NeoxaChain/Neoxa#20]
Hello,

I have been mining Neoxa since like 6 months. I have recently lost my laptop and I could not recover the data on my PC. So I bought new PC and I reconnected my Neoxa core wallet through my passphrase and mnemonic, after I can not find my balance in my wallet so I opened debug window from tools section and added my receiving address in which I have been mining. After that I can see my balance but it's not spendable its only watch only mode. Can anyone here help please?

<img width="922" alt="Screenshot 2023-01-18 at 8 04 07 PM" src="https://user-images.githubusercontent.com/122995753/213206672-35fd2c4b-f15c-41f9-8cc6-516f457d3992.png">

**Comment by shinary2** [comment]
Go to tools>repair wallet>rebuild index.
When still watch only, you have entered incorrect recoverypassphrase.
I would recommend to join discord and ask for help there.
https://discord.gg/hwCyssqC
