### ISSUE TITLE
Windows Cross Compile doesn't work

### ISSUE THREAD

**Issue by MotoAcidic** [NeoxaChain/Neoxa#25]
When trying to compile windows with Ubuntu 20 i get this error while following the docs for windows compile

make[5]: Leaving directory '/home/travis/Neoxa/depends/work/build/x86_64-w64-mingw32/gmp/6.1.2-c999a7b8425'
make[4]: Leaving directory '/home/travis/Neoxa/depends/work/build/x86_64-w64-mingw32/gmp/6.1.2-c999a7b8425'
make[3]: Leaving directory '/home/travis/Neoxa/depends/work/build/x86_64-w64-mingw32/gmp/6.1.2-c999a7b8425'
make[2]: Leaving directory '/home/travis/Neoxa/depends/work/build/x86_64-w64-mingw32/gmp/6.1.2-c999a7b8425'
make[1]: Leaving directory '/home/travis/Neoxa/depends/work/build/x86_64-w64-mingw32/gmp/6.1.2-c999a7b8425'
Postprocessing gmp...
Caching gmp...
Fetching v20181101.tar.gz from https://github.com/dashpay/bls-signatures/archive
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  724k    0  724k    0     0   416k      0 --:--:--  0:00:01 --:--:--  841k
/home/travis/Neoxa/depends/work/download/chia_bls-v20181101/v20181101.tar.gz.temp: OK
Extracting chia_bls...
/home/travis/Neoxa/depends/sources/v20181101.tar.gz: OK
Preprocessing chia_bls...
Configuring chia_bls...
/bin/sh: 1: cmake: not found
funcs.mk:244: recipe for target '/home/Neoxa/depends/work/build/x86_64-w64-mingw32/chia_bls/v20181101-cd627115668/./.stamp_configured' failed
make: *** [/home/Neoxa/depends/work/build/x86_64-w64-mingw32/chia_bls/v20181101-cd627115668/./.stamp_configured] Error 127

**Comment by AndyNeoxa** [comment]
Make sure you have cmake installed.
