### ISSUE TITLE
cannot use port other than 8788 on smartnodes

### ISSUE THREAD

**Issue by brossob** [NeoxaChain/Neoxa#26]
protx command will not allow any other port than 8788 , 

COMMAND USING PORT 8788 (works)
protx quick_setup "xxx" "1" "xxx.xxx.xxx.xxx:8788" "xxx"

{
  "txid": "x",
  "tx": "xxxx",
  "ownerAddress": "xxxx",
  "votingAddress": "xxxx",
  "payoutAddress": "xxxx",
  "collateralAddress": "Gxxxx",
  "collateralAmount": 1000000,
  "signedMessage": "xxxx",
  "operatorPublic": "xxxx",
  "operatorSecret": "xxxx",
  "neoxa.conf": "/home/xxxx_neoxa.conf"
}

COMMAND USING PORT 8799 (FAILS)
protx quick_setup "xxxx" "1" "xxx.xxx.xxx.xxx:8799" "xxxx"
bad-protx-ipaddr-port (code 16) (code -1)

if my port 8788 is in use , i want to be able to run my smartnode on another port

**Comment by shinary2** [comment]
This is not possible. The port is fixed on 8788 for Smartnodes on Neoxa chain.
