### ISSUE TITLE
New Wallet is NOT working!

### ISSUE THREAD

**Issue by Alan911Black** [NeoxaChain/Neoxa#27]
i was mining for a while and didn't pay attn that wallet has change, now after 3 days doing everything imagen...i still do not have my coins
i installed the New wallet 5.1.1.4 QT input my secret words, let it do his thing. update done NO COINS
i read on line to repair wallet, i tried all the options still 0 coins. i had over 5K coins that are now lost

any ideas, what to do? should i install lower version?
it sucks because you need to wait a day for the blockchain to update just to find out you have no coins.

anyone had this issue? what should i do

**Comment by Alan911Black** [comment]
> I have the same problem, not many coins as you, but around 2k, lost, same issues as you, exactly the same :( dunno how to get it back, later tonight I will try on metamask, i've heard neoxa is there too

please let me know if it works for you

**Comment by shinzon6795** [comment]
It seems I was misled by a shady website, but try the discord support

**Comment by shinary2** [comment]
Please join official discord and let you help, its much better than via "email" contact here :) there we got even a full guide and staff nearly 24/7 available for personal help.
https://discord.com/invite/frYkQqrAwR

**Comment by McA1992** [comment]
Hi I can´t join your discord support server. The Invitation link is not valid any more.

**Comment by shinary2** [comment]
https://discord.com/invite/frYkQqrAwR

> Hi I can´t join your discord support server. The Invitation link is not valid any more.

Thats odd, it a perma link that should always work, here you got a custom created from me:
https://discord.gg/CpmFmBE3
you can even do it from miningpoolstats, bottom right is a invite link
https://miningpoolstats.stream/neoxa

**Comment by McA1992** [comment]
Thank you for the quick response but i have no luck with your link or the invite link from miningpoolstats. It says always that it can't take the invitation. tested it with two different discord accounts and with 3 different browsers..

**Comment by shinary2** [comment]
Please try this way, the invite code is working fine and it looks like anything on your side is blocking it 
https://www.howtogeek.com/686597/how-to-clear-discord-cache-files-on-desktop-and-mobile/
Do you mind to share your discordID? Right click on your name and botton your should see in red " discord ID "
Maybe you don´t see it and need to activate dev-mod in settings>advanced. I will check if you are banned or anything else.

**Comment by McA1992** [comment]
Ok that would be really strange but here it is: 1131243454232543235

**Comment by shinary2** [comment]
Thanks, give me few minutes i checking out whats up.

**Comment by shinary2** [comment]
Please try once again to join via the link from miningpoolstats.
Restart the browser before.

**Comment by McA1992** [comment]
Ok that worked. Can you tell me what went wrong? My second account seems still blocked.

**Comment by shinary2** [comment]
I response already in discord.

**Comment by peyman2202** [comment]
Hello, I also opened the version 4 wallet after a while, I just realized that it can't be updated, I also got version 5, but I don't know how to transfer my assets to this new wallet, what should I do now?
