### ISSUE TITLE
I don't even know how to open my wallet

### ISSUE THREAD

**Issue by Springrass** [NeoxaChain/Neoxa#29]
![截屏2023-11-13 09 30 29](https://github.com/NeoxaChain/Neoxa/assets/65485088/8b98f953-8e9d-417f-b275-42b88748ffee)
Who can help me?

**Comment by 0x00ASTRA** [comment]
@Springrass On mac you need to download the [neoxad-5.1.1.4-osx.zip](https://github.com/NeoxaChain/Neoxa/releases/download/v5.1.1.4/neoxad-5.1.1.4-osx.zip) and unzip it. Drag the neoxa-qt file into the `neoxad-5.1.1.4-osx/` folder and open a terminal in the neoxad-5.1.1.4-osx folder. use `chmod +x *` to make them executables and then run `sudo ./neoxa-qt`. you may need to open setting and go into privacy and permissions to grant the executable permission to run on your machine.
