### ISSUE TITLE
Wallet doesn't work on MacOS

### ISSUE THREAD

**Issue by maxmetelitsa** [NeoxaChain/Neoxa#33]
I have downloaded the file for MacOS wallet (https://github.com/NeoxaChain/Neoxa/releases/download/v5.1.1.4/neoxaqt-5.1.1.4-osx.zip), so when you click on the file, the system just opens the text file an nothing happens.
<img width="676" alt="Снимок экрана 2023-11-26 в 23 34 18" src="https://github.com/NeoxaChain/Neoxa/assets/107760929/25b64879-f952-4e80-84ba-1d6817d53e98">

**Comment by yoztheripper** [comment]
Did you chmod +x neoxa-qt ?

**Comment by marvin0o** [comment]
Hello for me, the same issue I can't open the wallet on macosx (mac m1 max, sonoma 14,2).

With what program should I open this? 

Already chmod the file

**Comment by shinary2** [comment]
How to get the Neoxa-QT wallet working on MacOS:
Start the terminal in the folder where your neoxa-qt is and type
sudo chmod +x neoxa-qt
enter your system password and you should be able to open this file afterwards with a double click.
Video guide how to open a terminal: https://www.youtube.com/watch?v=IAmsq1ULvSk
