### ISSUE TITLE
How to properly update old wallet with new wallet in my laptop? Already deleted all files from old one, and still can't get the new wallet to work. Please help. Thanks.

### ISSUE THREAD

**Issue by k709944** [NeoxaChain/Neoxa#34]

**Comment by peyman2202** [comment]
Hello, I also opened the version 4 wallet after a while, I just realized that it can't be updated, I also got version 5, but I don't know how to transfer my assets to this new wallet, what should I do now?

**Comment by shinary2** [comment]
Wallet update from v4 to v5:
1 Open up your old wallet.
2 Go in wallet>view mnemonics, type in your unlock password for this wallet (the same as for sending coins)
3 Write your 12 words down (if you see a passphrase under the 12 words as in the pictures below, this is the recoverypassphrase. smaller bottom box at first window when starting the new version)
4 Download new versionhttps://github.com/NeoxaChain/Neoxa/releases/tag/v5.1.1.4 (QT = Gui, Neoxad = CLI/Daemon) and use a different folder as your old version, they are not compatible and you can´t recover with the wallet.dat on the new version.
5 Type in both boxes
6 Let it sync.
7 Tools > repair wallet > recover transactions 1
8 If you want to see previous address again: In "receive tab" checkmark "reuse a existing one (not recommended)" and click on "request payment". There you can choose which one you want to be shown again.
