### ISSUE TITLE
Transferring assets from wallet version 4 to wallet version 5

### ISSUE THREAD

**Issue by peyman2202** [NeoxaChain/Neoxa#35]
Hello, I also opened the version 4 wallet after a while, I just realized that it can't be updated, I also got version 5, but I don't know how to transfer my assets to this new wallet, what should I do now?

**Comment by shinary2** [comment]
Wallet update from v4 to v5:
1 Open up your old wallet.
2 Go in wallet>view mnemonics, type in your unlock password for this wallet (the same as for sending coins)
3 Write your 12 words down (if you see a passphrase under the 12 words as in the pictures below, this is the recoverypassphrase. smaller bottom box at first window when starting the new version)
4 Download new versionhttps://github.com/NeoxaChain/Neoxa/releases/tag/v5.1.1.4 (QT = Gui, Neoxad = CLI/Daemon) and use a different folder as your old version, they are not compatible and you can´t recover with the wallet.dat on the new version.
5 Type in both boxes 
6 Let it sync.
7 Tools > repair wallet > recover transactions 1
8 If you want to see previous address again: In "receive tab" checkmark "reuse a existing one (not recommended)" and click on "request payment". There you can choose which one you want to be shown again.

**Comment by peyman2202** [comment]
> Wallet update from v4 to v5: 1 Open up your old wallet. 2 Go in wallet>view mnemonics, type in your unlock password for this wallet (the same as for sending coins) 3 Write your 12 words down (if you see a passphrase under the 12 words as in the pictures below, this is the recoverypassphrase. smaller bottom box at first window when starting the new version) 4 Download new versionhttps://github.com/NeoxaChain/Neoxa/releases/tag/v5.1.1.4 (QT = Gui, Neoxad = CLI/Daemon) and use a different folder as your old version, they are not compatible and you can´t recover with the wallet.dat on the new version. 5 Type in both boxes 6 Let it sync. 7 Tools > repair wallet > recover transactions 1 8 If you want to see previous address again: In "receive tab" checkmark "reuse a existing one (not recommended)" and click on "request payment". There you can choose which one you want to be shown again.

Thank you for your guidance.
I entered the 12 recovery words in the version 4 wallet as it was written with a space between each word in the first two windows of the version 5 wallet and let the wallet be universalized. I hit transaction 1 but nothing came up and my balance is still zero.
What should I do now?

**Comment by shinary2** [comment]
The easiest way would be join Neoxa discord and ping me "shinary" in support channel please. 
This is the best way to have a support discussion, compared to email talk here :D

**Comment by peyman2202** [comment]
> The easiest way would be join Neoxa discord and ping me "shinary" in support channel please. This is the best way to have a support discussion, compared to email talk here :D https://discord.com/invite/frYkQqrAwR

Thank you dear friend.
Because I don't know English well, I work with google translation, it's hard for me to speak in the group.
If you can help me to recover the currency, I will be grateful. I have tried all the methods, but none of them worked and all my balance is stuck in the version 4 wallet.

**Comment by shinary2** [comment]
Wallet update/recovery not succeed (no balance available) and feel lost? TRY THIS!
1. Go in your new wallet tools>debug console and type
validateaddress GPrpcxydHNiUGcgJYizV3mUx3C6PRkb9d4
Replace with a address of your own and coins within.
you get a output "ismine=" true or false.
when you get true, tools>repair wallet>recover transactions 1
If its false:
2. close wallet, delete wallet.dat in your new version wallet  (default folder in Windows is %appdata%\neoxacore and for MAC "/Library/Application Support/neoxacore" or check in tools>information for datadir)
3. restart wallet
4. there are 3 options what you could have used for 2nd box (recovery passphase)
     1         nothing, leave it empty
     2        same 12 words as for top 1st box
     3        any password you have set on your own ( maybe any common one and only you know it )
5. Proceed again with "validateaddress" command
Continue this process as long until you get "ismine : true" and recover transactions 1 in tools>repair wallet.
