### ISSUE TITLE
Compile erros

### ISSUE THREAD

**Issue by Namp88** [NeoxaChain/Neoxa#36]
Hi everyone. I get this error when I do `make` (Ubuntu 22.04). I tried different releases, but I got the same result.

![image](https://github.com/NeoxaChain/Neoxa/assets/33064857/f9fbd613-6767-44d0-9ea7-85d7d6f2c18e)

**Comment by shinary2** [comment]
You could use the precompiled CLI version, or is it necessary to compile for yourself?
