### ISSUE TITLE
MinGW Assertion failed! evo/evodb.cpp, Line 71 hashBestBlock==hashBlockIndex

### ISSUE THREAD

**Issue by MisterDeeds** [NeoxaChain/Neoxa#40]
Hello everyone

My Neoxa Core Wallet has not been working properly for a few days now. The following message appears when I open it:

![Wallet](https://github.com/user-attachments/assets/10ccc9dd-2849-4e05-aea5-113b997b23c4)

Does anyone have a solution?

Thank you and best regards

**Comment by shinary2** [comment]
Close wallet. Remove all files and keep wallet.dat in %appdata%\neoxacore folder (if choosed custom one, remove in custom). But keep your wallet.dat and backups folder! This is your file with coins in it.
Unzip all files in the neoxacore folder and start wallet.
Link to bootstrap: https://fastupload.io/0df802d721e1ec60
If you don´t want to use the bootstrap, just start the wallet after removing the blockchain files and wait for sync.

**Comment by MisterDeeds** [comment]
Dear shinary2

Thanks for the tip. It has now worked. I copied the “NeoxaCore” folder from %appdata% and synchronized the wallet again. Then I closed it and copied the “wallet.dat” back, started it, everything is back and working! 

Thank you very much!
