### ISSUE TITLE
neoxa-qt.exe crashes at stratup when -disablewallet is used

### ISSUE THREAD

**Issue by gdcfxvnjvbncvb** [NeoxaChain/Neoxa#5]
Hello,

When using neoxa-qt.exe, from neoxa-qt-win64.zip, with the option -disablewallet, it crashes at startup.

Kind regards,
gdcfxvnjvbncvb

**Comment by shinary2** [comment]
Why you wanna -disablewallet in a wallet?

**Comment by gdcfxvnjvbncvb** [comment]
Just to run it as a node. And as I understood, with that option, the software takes up less resources (CPU/RAM). Also, no need to re-sync the addresses contained in the wallet, in case of a problem.

**Comment by shinary2** [comment]
Than i would suggest to run neoxad, thats the deamon, the qt is wallet and guess it will crash as you try to run as a node only ;)
