### ISSUE TITLE
Neoxa

### ISSUE THREAD

**Issue by Malik0120** [NeoxaChain/Neoxa#6]

**Comment by neirymarm** [comment]
Hello, I am Spanish, I did not refresh the page in 25 weeks and the computer does not update, what should I do?

**Comment by neirymarm** [comment]
I have been trying to get it to work for 1 week, but it doesn't load, what should I do please, I can't get any number to help me solve the problem, I think I'll lose all my money

**Comment by shinary2** [comment]
> I have been trying to get it to work for 1 week, but it doesn't load, what should I do please, I can't get any number to help me solve the problem, I think I'll lose all my money

1. click on Tool's and then Debug Window.
INPUT COMMANDS AT THE BOTTOM
2.  Type 
clearbanned
 and hit enter.
3. Remove the follow nodes. You can copy and past the hole list at once. Hit enter.
addnode 184.70.53.6:8788 remove
addnode 142.115.20.25:8788 remove
addnode 142.115.20.25:8790 remove
addnode 65.108.246.133:8788 remove
addnode 95.216.145.191:8788 remove
addnode 139.177.197.92:8788 remove
addnode 185.9.146.1212:8788 remove
addnode 45.136.29.237:8788 remove
addnode 94.63.21.104:8788 remove
addnode 142.132.229.5:8788 remove
addnode 164.68.100.209:8788 remove
addnode 80.2.135.187:8788 remove
addnode 88.152.155.58:8788 remove
addnode 165.227.137.52:8788 remove
addnode 207.154.203.174:8788 remove

4. Add the nodes back. This will force them to talk again. It can still take time for nodes to connect. But keep checking your peers on the peers tab. 
addnode 184.70.53.6:8788 add
addnode 142.115.20.25:8788 add
addnode 142.115.20.25:8790 add 
addnode 65.108.246.133:8788 add
addnode 95.216.145.191:8788 add
addnode 139.177.197.92:8788 add
addnode 185.9.146.1212:8788 add
addnode 45.136.29.237:8788 add
addnode 94.63.21.104:8788 add
addnode 142.132.229.5:8788 add
addnode 164.68.100.209:8788 add
addnode 80.2.135.187:8788 add
addnode 88.152.155.58:8788 add
addnode 165.227.137.52:8788 add
addnode 207.154.203.174:8788 add
