### ISSUE TITLE
Testnet 

### ISSUE THREAD

**Issue by Konstantin35** [NeoxaChain/Neoxa#7]
Do you have a test network?

**Comment by HarveyNeoxa** [comment]
Testnet is online and active, please use testnet flag.

**Comment by Konstantin35** [comment]
does not work
```
neox@s486059:~/pool$ ./neoxa-cli getblocktemplate
error code: -9
error message:
Neoxa is not connected!
```

**Comment by rlinxy** [comment]
Same here, can't connect to any peer on testnet. We are developping a mining pool, really need a testnet for it.

**Comment by AndyNeoxa** [comment]
Hi, this will be fixed shortly.
