### ISSUE TITLE
Please document how to get the wallet address for mining

### ISSUE THREAD

**Issue by DeeDeeRanged** [NeoxaChain/Neoxa#9]
Please document how to get the wallet address from Neoxa-wallet so it can be used for mining as documentation seems to be a bit scarce. That would help a lot of first users mining for NEOXA.

**Comment by fattycheeks** [comment]
SAME!  I have no clue how to get this wallet address!

**Comment by shinary2** [comment]
Hey guys, open the wallet.
Head over left menu for receive and click on request payment.
Address generated :)

**Comment by NikheelR97** [comment]
If you didnt manage to create a receiving address.

On macOS

On the menu bar, click on "File"
Then click on "Receiving Addresses"
Then click on "New"
In the "Label" field add in whatever you want to name your wallet as
Leave address blank
Click on "Ok"
You will see your mining wallet and address on the window now. 
Click on the "Copy" button on the bottom right side to copy the wallet to your clip board.
address now created :)
